baseURL = "https://example.com"
languageCode = "en-us"
title = "ZenHo"
theme = "hugo-zenHo"
paginate = 6
enableEmoji = true

[params]
    enableToc = false

    enableBaiduAnalytics = false
    baiduAnalyticsToken = ""

    googleSiteVerificationToken = ""

    enableSummary = true
    useDescriptionReplaceSummary = true

    author  = "vran"
    bio = "All good things come to thos who wait."

    github = "#"
    twitter = "#"
    facebook = "#"
    email = "example@example.com"

    enableUtteranc = false 
    [params.utteranc]
        repo="username/repository-name"
        theme="github-light"
        crossorigin="anonymous"
        issueTerm="pathname"
        label="Comment"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
  [markup.highlight]
    style = "xcode"
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
